# Generated by Django 5.2.3 on 2025-06-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_venda', models.CharField(choices=[('m2', 'Metro quadrado (m²)'), ('m3', 'Metro cúbico (m³)'), ('saco', 'Saco'), ('kg', 'Quilograma (kg)'), ('unid', 'Unidade')], max_length=10)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria')),
            ],
        ),
    ]
