# Generated by Django 5.2.1 on 2025-06-16 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/images/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_venda', models.CharField(choices=[('m2', 'Metro quadrado (m²)'), ('m3', 'Metro cúbico (m³)'), ('saco', 'Saco'), ('kg', 'Quilograma (kg)'), ('unid', 'Unidade')], max_length=10)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'tipo': 'fornecedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
